name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - review-3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: madec1st
          password: ${{ secrets.FILM_TOKEN }}
          
      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.frontend
          push: true
          tags: ghcr.io/madec1st/film-react-nest/frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile.backend
          push: true
          tags: ghcr.io/madec1st/film-react-nest/backend:latest
